---
__postgresql_cluster_name: "main_cluster"
__postgresql_cluster_port: "5433"
__postgresql_cluster_version: "12"
__postgresql_pg_auto_failover_version: "1.4"
__postgresql_repository: "deb [ arch=amd64 ] http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
__postgresql_cluster_data_dir: "/var/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_bin_path: "/usr/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/bin"
__postgresql_cluster_config_path: "/var/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_daemon: "postgresql_{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_packages:
  - "postgresql-{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}"
  - "postgresql-contrib-{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}"
  - libpq-dev
postgresql_cluster_python_library: python3-psycopg2
